#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=2
#SBATCH --job-name=RecosWalker
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --time=01:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

cd $HOME/Homophilic_Directed_ScaleFree_Networks


source activate lr_env_v4

# srun python generate_recos_real_ds_model_based.py --model  ffw  --name pokec --seed 42



